// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoApi.Models;

#nullable disable

namespace TodoApi.Migrations
{
    [DbContext(typeof(TodoContext))]
    [Migration("20220904112912_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("TodoApi.Models.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Secret")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TodoItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsComplete = false,
                            Name = "Task 1",
                            Secret = "Secret 1"
                        },
                        new
                        {
                            Id = 2,
                            IsComplete = false,
                            Name = "Task 2",
                            Secret = "Secret 2"
                        },
                        new
                        {
                            Id = 3,
                            IsComplete = true,
                            Name = "Task 3",
                            Secret = "Secret 3"
                        },
                        new
                        {
                            Id = 4,
                            IsComplete = true,
                            Name = "Task 4",
                            Secret = "Secret 4"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
